### ISSUE TITLE
Description and Spotify Page

### ISSUE THREAD

**Issue by sjChen15** [sjChen15/MusicToned#13]
Tells you what the app does/icon and then something to get you to authorize Spotify if has not been done before.

Front end to: #2

**Comment by daltonbown01** [comment]
@sdepol So for this task I think there are two things I'll need for this one:

- Mock of the welcome flow. I was thinking maybe two pages? The first one is a welcome screen that briefly describes the app with the logo and the second is just the Spotify linker page that has a button. The button would need to follow Spotify's guidelines on messaging:

> How to link to Spotify
If the Spotify app is not installed then the link should say, GET SPOTIFY FREE
If the Spotify app is installed then use any of the following text strings: OPEN SPOTIFY, PLAY ON SPOTIFY or LISTEN ON SPOTIFY
The link to Spotify must follow [Spotify's attribution requirements](https://developer.spotify.com/documentation/design#attribution) and be accessible in your companion app.

- Logo asset

**Comment by notharshp** [comment]
self-assigning myself to this one as I am working on spotify integration and I need to give the app authorization to link spotify.

**Comment by daltonbown01** [comment]
@notharshp Sounds like you're taking the Spotify portion of this work then? So maybe I'll just focus on the actual welcome flow I suppose?

**Comment by daltonbown01** [comment]
Merged the placeholders for the other screens to unblock others. Just working on the conditional routing based on the Spotify state now
