### ISSUE TITLE
Create mocks

### ISSUE THREAD

**Issue by sjChen15** [sjChen15/MusicToned#5]
IDK would Steph like to fill this ticket out :)

**Comment by sdepol** [comment]
Here are all of the Figma files created for this project: [https://www.figma.com/files/project/93875320/Team-project?fuid=971229951051158006 ](https://www.figma.com/files/project/93875320/Team-project?fuid=971229951051158006 )

Here are the UI/UX design mocks created for the app: [https://www.figma.com/file/ZZtViDeRcg6VMhmt02ydJ6/Mockup?type=design&node-id=0%3A1&mode=design&t=k8QgpRDocq7mo0YS-1](https://www.figma.com/file/ZZtViDeRcg6VMhmt02ydJ6/Mockup?type=design&node-id=0%3A1&mode=design&t=k8QgpRDocq7mo0YS-1)
