### ISSUE TITLE
Research and decide what workouts to include in our app (then make assets)

### ISSUE THREAD

**Issue by sjChen15** [sjChen15/MusicToned#6]
Choose a number of basic work outs to add to our app and research the ideal BMP to do them at. Must choose workouts that have tempo data. 

Maybe download Nike workout app and see what they have there (Competition research). 

Start with workouts without machine. Then add weights. Then add machines. 

Min 25 Max 50

**Comment by sjChen15** [comment]
We also need to know the calories burned doing the exercise. I know if you do it faster it would burn more calories but it would be easier to set one calorie value for each workout. ie one pushup burns 0.32 calories

**Comment by sdepol** [comment]
Done, uploaded 57 workouts. Used MET scoring for calorie calculations: 
Calories Burned = time*MET*3.5*(your body weight in kilograms / 200)
